server:
  port: ${PORT:8080}

spring:
  application:
    name: mainichi-pos-api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.mainichi.pos: DEBUG
    org.springframework.jdbc.core: DEBUG
